name: The Barbarian Philosopher
favicon: null
layout_spectrum: 0.188172
typography_spectrum: 0.8178017
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6A8DCF'
    - '#FFFFFF'
    - '#8AB4E8'
    - '#222F37'
    - '#4C6687'
  brandStrength: 0.4233120169956237
  lightness: 0.439429180463776
  saturation: 0.9060709825716913
  rhythmicContrast: 0.5069999534171075
purpose: []
